data_dir: /var/lib/vector
api:
  enabled: true
  address: 0.0.0.0:8686
  playground: true
telemetry:
  metrics:
    enabled: true
sources:
  http_in:
    type: http_server
    address: 0.0.0.0:8081
transforms:
  parse_logs:
    type: remap
    inputs:
      - http_in
    source: |
      # Thử parse JSON, nếu thành công thì merge, nếu không thì giữ nguyên
      parsed, err = parse_json(.message)
      if err == null {
        . = merge!(., parsed)
      }
      # Đảm bảo có timestamp
      if !exists(.timestamp) {
        .timestamp = now()
      }
  enrich_tag:
    type: remap
    inputs:
      - parse_logs
    source: |
      .pipeline = "demo"
      if !exists(.source_type) {
        .source_type = "unknown"
      }
  reduce_keep:
    type: remap
    inputs:
      - enrich_tag
    source: |
      . = {
        "timestamp": .timestamp,
        "message": .message,
        "pipeline": .pipeline,
        "source_type": .source_type
      }

      # Thêm container_name chỉ nếu tồn tại (cho Docker logs)
      if exists(.container_name) {
        .container_name = .container_name
      }
sinks:
  console_debug:
    type: console
    inputs:
      - reduce_keep
    encoding:
      codec: json
  s3_output:
    type: aws_s3
    inputs:
      - reduce_keep
    bucket: phucnguyen204
    region: ap-southeast-2
    key_prefix: http-logs/%Y/%m/%d/
    compression: gzip
    encoding:
      codec: json
    batch:
      max_events: 1
      timeout_secs: 10
