data_dir: /var/lib/vector
api:
  enabled: true
  address: 0.0.0.0:8686
  playground: false
telemetry:
  metrics:
    enabled: true
sources:
  http_source2:
    type: http_server
    address: 0.0.0.0:8081
transforms:
  http_source2_parse_0:
    type: remap
    inputs:
      - http_source2
    source: |
      # Thử parse JSON, nếu thành công thì merge, nếu không thì giữ nguyên
      parsed, err = parse_json(.message)
      if err == null {
        . = merge!(., parsed)
      }
      # Đảm bảo có timestamp
      if !exists(.timestamp) {
        .timestamp = now()
      }
sinks:
  http_source2_console_0:
    type: console
    inputs:
      - http_source2_parse_0
    encoding:
      codec: json
